# Site settings
# in the templates available like {{ site.myvariable }}.
title: 
email: your-email@domain.com
brand: Dr. Kumar Shubham
headline: HOD & Associate Professor, Delhi Technical Campus
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site
copyright: 2018, 

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: mmmecasthana@gmail.com
phone: +91 8765370450

# Tracking
googleAnalitycsID: UA-83933844-1

