# Site settings
# in the templates available like {{ site.myvariable }}.
title: My Personal Website
email: rohwchawla@gmail.com
brand: ROHIT  CHAWLA
headline: 
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site


# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: rohwchawla@gmail.com
phone: +91-8824948368



